### ISSUE TITLE
在执行npm run dev的时候 出现如下错误

### ISSUE THREAD

**Issue by eighteen20** [Momo707577045/vue-circle-progress#2]
This dependency was not found:
* !!vue-style-loader!css-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-7ba5bd90","scoped":true,"hasInline","scoped":true,"hasInlineConfig":false}!sass-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue in ./src/App.vue.
解决：
npm install sass-loader --save
npm install node-sass --save
然后运行npm run dev就可以

**Comment by MuLoo** [comment]
即使执行了 @eighteen20 所说的之后，还是可能会报错
`Module build failed: TypeError: this.getResolve is not a function`

sass-loader的版本过高导致的编译错误，当前最高版本是8.x，需要退回到7.3.1
运行：`npm uninstall sass-loader（卸载当前版本）`
　　　`npm install sass-loader@7.3.1 --save-dev`

**Comment by eighteen20** [comment]
> 即使执行了 @eighteen20 所说的之后，还是可能会报错
> `Module build failed: TypeError: this.getResolve is not a function`
> 
> sass-loader的版本过高导致的编译错误，当前最高版本是8.x，需要退回到7.3.1
> 运行：`npm uninstall sass-loader（卸载当前版本）`
> 　　　`npm install sass-loader@7.3.1 --save-dev`

我当时没注意版本问题，谢谢提醒
